jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
                scope: GLOBAL
                id: github_read
                username: shane-mulcair
                password: ""